name: Docker Build And Push To Docker Hub

on:
  push:
    branches: [ main ]
    tags:
     - v**

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      repo: ${{github.event.repository.name}}
      APP_NAME: ${repo:6}
      TAGNAME: latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
         
      - name: Get all tags
        if: ${{ github.ref_name != 'main' }}
        run: |
         tmptag=${{ github.ref_name}}
         arraytag=(${tmptag//./})
         TAGNAME=${arraytag[0]},${arraytag[1]},${{ github.ref_name}},latest
         
         echo $TAGNAME

