name: CI

on:
  push:
      paths: [README-zh.jinja2, README.jinja2]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env:
          FILES:  docker-akeneo 
                  docker-alfresco
                  docker-awx
                  docker-bigbluebutton
                  docker-caddy
                  docker-cloudbeaver
                  docker-cmak
                  docker-codeserver
                  docker-couchdb
                  docker-dgraph
                  docker-drupal
                  docker-elasticsearch
                  docker-elk
                  docker-erpnext
                  docker-falcon
                  docker-geoserver
                  docker-gitlab
                  docker-gogs
                  docker-grafana
                  docker-graylog
                  docker-guacamole
                  docker-haproxy
                  docker-httpd
                  docker-influxdata
                  docker-jenkins
                  docker-jetty
                  docker-joomla
                  docker-jumpserver
                  docker-jupyter
                  docker-kafka
                  docker-kibana
                  docker-knowage
                  docker-logstash
                  docker-magento
                  docker-mariadb
                  docker-mattermost
                  docker-mautic
                  docker-mediawiki
                  docker-memcached
                  docker-memadmin
                  docker-metabase
                  docker-mingdao
                  docker-mongodb
                  docker-mongoexpress
                  docker-moodle
                  docker-mysql
                  docker-neo4j
                  docker-nextcloud
                  docker-nginx
                  docker-odoo
                  docker-onlyoffice
                  docker-onlyofficedocumentserver
                  docker-opencart
                  docker-owncloud
                  docker-pgadmin
                  docker-phpmyadmin
                  docker-pimcore
                  docker-portainer
                  docker-postgresql
                  docker-prestashop
                  docker-projector
                  docker-rabbitmq
                  docker-redis
                  docker-redmine
                  docker-rethinkdb
                  docker-rocketchat
                  docker-saleor
                  docker-seafile
                  docker-server
                  docker-strapi
                  docker-superset
                  docker-template
                  docker-theia
                  docker-tomcat
                  docker-varnish
                  docker-wordpress
                  docker-xwiki
                  docker-zentao
                  docker-zabbix
        run: |
          for f in $FILES
          do
            curl -X POST https://api.github.com/repos/websoft9/$f/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACCESS_TOKEN }} \
            --data '{"event_type": "sync_readme", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          done
