name: CI

on:
  push:
      paths: [README-zh.jinja2, README.jinja2]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env:
          FILES: docker-codeserver
        run: |
          for f in $FILES
          do
            curl -X POST https://api.github.com/repos/websoft9/f/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -u ${{ secrets.ACCESS_TOKEN }} \
            --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
          done
